# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alvaregd/Documents/Games/hardware_skinning

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alvaregd/Documents/Games/hardware_skinning

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alvaregd/Documents/Games/hardware_skinning/CMakeFiles /home/alvaregd/Documents/Games/hardware_skinning/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alvaregd/Documents/Games/hardware_skinning/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hardware_skinning

# Build rule for target.
hardware_skinning: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hardware_skinning
.PHONY : hardware_skinning

# fast build rule for target.
hardware_skinning/fast:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/build
.PHONY : hardware_skinning/fast

camera/camera.o: camera/camera.cpp.o
.PHONY : camera/camera.o

# target to build an object file
camera/camera.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/camera/camera.cpp.o
.PHONY : camera/camera.cpp.o

camera/camera.i: camera/camera.cpp.i
.PHONY : camera/camera.i

# target to preprocess a source file
camera/camera.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/camera/camera.cpp.i
.PHONY : camera/camera.cpp.i

camera/camera.s: camera/camera.cpp.s
.PHONY : camera/camera.s

# target to generate assembly for a file
camera/camera.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/camera/camera.cpp.s
.PHONY : camera/camera.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/main.cpp.s
.PHONY : main.cpp.s

mesh/mesh.o: mesh/mesh.cpp.o
.PHONY : mesh/mesh.o

# target to build an object file
mesh/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/mesh/mesh.cpp.o
.PHONY : mesh/mesh.cpp.o

mesh/mesh.i: mesh/mesh.cpp.i
.PHONY : mesh/mesh.i

# target to preprocess a source file
mesh/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/mesh/mesh.cpp.i
.PHONY : mesh/mesh.cpp.i

mesh/mesh.s: mesh/mesh.cpp.s
.PHONY : mesh/mesh.s

# target to generate assembly for a file
mesh/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/mesh/mesh.cpp.s
.PHONY : mesh/mesh.cpp.s

platform/glfw_launcher.o: platform/glfw_launcher.cpp.o
.PHONY : platform/glfw_launcher.o

# target to build an object file
platform/glfw_launcher.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/platform/glfw_launcher.cpp.o
.PHONY : platform/glfw_launcher.cpp.o

platform/glfw_launcher.i: platform/glfw_launcher.cpp.i
.PHONY : platform/glfw_launcher.i

# target to preprocess a source file
platform/glfw_launcher.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/platform/glfw_launcher.cpp.i
.PHONY : platform/glfw_launcher.cpp.i

platform/glfw_launcher.s: platform/glfw_launcher.cpp.s
.PHONY : platform/glfw_launcher.s

# target to generate assembly for a file
platform/glfw_launcher.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/platform/glfw_launcher.cpp.s
.PHONY : platform/glfw_launcher.cpp.s

skybox/skybox.o: skybox/skybox.cpp.o
.PHONY : skybox/skybox.o

# target to build an object file
skybox/skybox.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/skybox/skybox.cpp.o
.PHONY : skybox/skybox.cpp.o

skybox/skybox.i: skybox/skybox.cpp.i
.PHONY : skybox/skybox.i

# target to preprocess a source file
skybox/skybox.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/skybox/skybox.cpp.i
.PHONY : skybox/skybox.cpp.i

skybox/skybox.s: skybox/skybox.cpp.s
.PHONY : skybox/skybox.s

# target to generate assembly for a file
skybox/skybox.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/skybox/skybox.cpp.s
.PHONY : skybox/skybox.cpp.s

utils/io/shader_loader.o: utils/io/shader_loader.cpp.o
.PHONY : utils/io/shader_loader.o

# target to build an object file
utils/io/shader_loader.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/shader_loader.cpp.o
.PHONY : utils/io/shader_loader.cpp.o

utils/io/shader_loader.i: utils/io/shader_loader.cpp.i
.PHONY : utils/io/shader_loader.i

# target to preprocess a source file
utils/io/shader_loader.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/shader_loader.cpp.i
.PHONY : utils/io/shader_loader.cpp.i

utils/io/shader_loader.s: utils/io/shader_loader.cpp.s
.PHONY : utils/io/shader_loader.s

# target to generate assembly for a file
utils/io/shader_loader.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/shader_loader.cpp.s
.PHONY : utils/io/shader_loader.cpp.s

utils/io/stb_image.o: utils/io/stb_image.cpp.o
.PHONY : utils/io/stb_image.o

# target to build an object file
utils/io/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/stb_image.cpp.o
.PHONY : utils/io/stb_image.cpp.o

utils/io/stb_image.i: utils/io/stb_image.cpp.i
.PHONY : utils/io/stb_image.i

# target to preprocess a source file
utils/io/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/stb_image.cpp.i
.PHONY : utils/io/stb_image.cpp.i

utils/io/stb_image.s: utils/io/stb_image.cpp.s
.PHONY : utils/io/stb_image.s

# target to generate assembly for a file
utils/io/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/stb_image.cpp.s
.PHONY : utils/io/stb_image.cpp.s

utils/io/stb_image_write.o: utils/io/stb_image_write.cpp.o
.PHONY : utils/io/stb_image_write.o

# target to build an object file
utils/io/stb_image_write.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/stb_image_write.cpp.o
.PHONY : utils/io/stb_image_write.cpp.o

utils/io/stb_image_write.i: utils/io/stb_image_write.cpp.i
.PHONY : utils/io/stb_image_write.i

# target to preprocess a source file
utils/io/stb_image_write.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/stb_image_write.cpp.i
.PHONY : utils/io/stb_image_write.cpp.i

utils/io/stb_image_write.s: utils/io/stb_image_write.cpp.s
.PHONY : utils/io/stb_image_write.s

# target to generate assembly for a file
utils/io/stb_image_write.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/stb_image_write.cpp.s
.PHONY : utils/io/stb_image_write.cpp.s

utils/io/texture.o: utils/io/texture.cpp.o
.PHONY : utils/io/texture.o

# target to build an object file
utils/io/texture.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/texture.cpp.o
.PHONY : utils/io/texture.cpp.o

utils/io/texture.i: utils/io/texture.cpp.i
.PHONY : utils/io/texture.i

# target to preprocess a source file
utils/io/texture.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/texture.cpp.i
.PHONY : utils/io/texture.cpp.i

utils/io/texture.s: utils/io/texture.cpp.s
.PHONY : utils/io/texture.s

# target to generate assembly for a file
utils/io/texture.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/texture.cpp.s
.PHONY : utils/io/texture.cpp.s

utils/io/video.o: utils/io/video.cpp.o
.PHONY : utils/io/video.o

# target to build an object file
utils/io/video.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/video.cpp.o
.PHONY : utils/io/video.cpp.o

utils/io/video.i: utils/io/video.cpp.i
.PHONY : utils/io/video.i

# target to preprocess a source file
utils/io/video.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/video.cpp.i
.PHONY : utils/io/video.cpp.i

utils/io/video.s: utils/io/video.cpp.s
.PHONY : utils/io/video.s

# target to generate assembly for a file
utils/io/video.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/io/video.cpp.s
.PHONY : utils/io/video.cpp.s

utils/log_utils/logger.o: utils/log_utils/logger.cpp.o
.PHONY : utils/log_utils/logger.o

# target to build an object file
utils/log_utils/logger.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/log_utils/logger.cpp.o
.PHONY : utils/log_utils/logger.cpp.o

utils/log_utils/logger.i: utils/log_utils/logger.cpp.i
.PHONY : utils/log_utils/logger.i

# target to preprocess a source file
utils/log_utils/logger.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/log_utils/logger.cpp.i
.PHONY : utils/log_utils/logger.cpp.i

utils/log_utils/logger.s: utils/log_utils/logger.cpp.s
.PHONY : utils/log_utils/logger.s

# target to generate assembly for a file
utils/log_utils/logger.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/log_utils/logger.cpp.s
.PHONY : utils/log_utils/logger.cpp.s

utils/math_utils/maths_funcs.o: utils/math_utils/maths_funcs.cpp.o
.PHONY : utils/math_utils/maths_funcs.o

# target to build an object file
utils/math_utils/maths_funcs.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/math_utils/maths_funcs.cpp.o
.PHONY : utils/math_utils/maths_funcs.cpp.o

utils/math_utils/maths_funcs.i: utils/math_utils/maths_funcs.cpp.i
.PHONY : utils/math_utils/maths_funcs.i

# target to preprocess a source file
utils/math_utils/maths_funcs.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/math_utils/maths_funcs.cpp.i
.PHONY : utils/math_utils/maths_funcs.cpp.i

utils/math_utils/maths_funcs.s: utils/math_utils/maths_funcs.cpp.s
.PHONY : utils/math_utils/maths_funcs.s

# target to generate assembly for a file
utils/math_utils/maths_funcs.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/math_utils/maths_funcs.cpp.s
.PHONY : utils/math_utils/maths_funcs.cpp.s

utils/math_utils/quat_funcs.o: utils/math_utils/quat_funcs.cpp.o
.PHONY : utils/math_utils/quat_funcs.o

# target to build an object file
utils/math_utils/quat_funcs.cpp.o:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/math_utils/quat_funcs.cpp.o
.PHONY : utils/math_utils/quat_funcs.cpp.o

utils/math_utils/quat_funcs.i: utils/math_utils/quat_funcs.cpp.i
.PHONY : utils/math_utils/quat_funcs.i

# target to preprocess a source file
utils/math_utils/quat_funcs.cpp.i:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/math_utils/quat_funcs.cpp.i
.PHONY : utils/math_utils/quat_funcs.cpp.i

utils/math_utils/quat_funcs.s: utils/math_utils/quat_funcs.cpp.s
.PHONY : utils/math_utils/quat_funcs.s

# target to generate assembly for a file
utils/math_utils/quat_funcs.cpp.s:
	$(MAKE) -f CMakeFiles/hardware_skinning.dir/build.make CMakeFiles/hardware_skinning.dir/utils/math_utils/quat_funcs.cpp.s
.PHONY : utils/math_utils/quat_funcs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hardware_skinning"
	@echo "... camera/camera.o"
	@echo "... camera/camera.i"
	@echo "... camera/camera.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mesh/mesh.o"
	@echo "... mesh/mesh.i"
	@echo "... mesh/mesh.s"
	@echo "... platform/glfw_launcher.o"
	@echo "... platform/glfw_launcher.i"
	@echo "... platform/glfw_launcher.s"
	@echo "... skybox/skybox.o"
	@echo "... skybox/skybox.i"
	@echo "... skybox/skybox.s"
	@echo "... utils/io/shader_loader.o"
	@echo "... utils/io/shader_loader.i"
	@echo "... utils/io/shader_loader.s"
	@echo "... utils/io/stb_image.o"
	@echo "... utils/io/stb_image.i"
	@echo "... utils/io/stb_image.s"
	@echo "... utils/io/stb_image_write.o"
	@echo "... utils/io/stb_image_write.i"
	@echo "... utils/io/stb_image_write.s"
	@echo "... utils/io/texture.o"
	@echo "... utils/io/texture.i"
	@echo "... utils/io/texture.s"
	@echo "... utils/io/video.o"
	@echo "... utils/io/video.i"
	@echo "... utils/io/video.s"
	@echo "... utils/log_utils/logger.o"
	@echo "... utils/log_utils/logger.i"
	@echo "... utils/log_utils/logger.s"
	@echo "... utils/math_utils/maths_funcs.o"
	@echo "... utils/math_utils/maths_funcs.i"
	@echo "... utils/math_utils/maths_funcs.s"
	@echo "... utils/math_utils/quat_funcs.o"
	@echo "... utils/math_utils/quat_funcs.i"
	@echo "... utils/math_utils/quat_funcs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

